/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz.application;

/**
 *
 * @author Lenovo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        txt6 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("Register");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 10, 150, 50);

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 144, 254));
        jLabel3.setText("Email Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 170, 130, 30);

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 144, 254));
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 120, 30);

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 144, 254));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 210, 120, 30);

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 144, 254));
        jLabel6.setText("Phone Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 250, 130, 30);

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 144, 254));
        jLabel7.setText("UserId");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 290, 120, 30);

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 144, 254));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 330, 120, 30);

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 144, 254));
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 130, 120, 30);

        pass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(pass);
        pass.setBounds(270, 330, 170, 30);

        txt6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt6);
        txt6.setBounds(270, 290, 170, 30);

        txt3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt3);
        txt3.setBounds(270, 170, 170, 30);

        txt4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt4);
        txt4.setBounds(270, 210, 170, 30);

        txt5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt5);
        txt5.setBounds(270, 250, 170, 30);

        txt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt1);
        txt1.setBounds(270, 90, 170, 30);

        txt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt2);
        txt2.setBounds(270, 130, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ss.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 20, 710, 480);

        jButton1.setBackground(new java.awt.Color(30, 144, 254));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 410, 130, 30);

        jButton2.setBackground(new java.awt.Color(30, 144, 254));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 410, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
}
